<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIszxoph\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIszxoph/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIszxoph.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIszxoph\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIszxoph\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Iszxoph',
    'container.build_id' => '9bf3a1ff',
    'container.build_time' => 1644847932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIszxoph');
